### ISSUE TITLE
How do you come up with project ideas?

### ISSUE THREAD

**Issue by sholladay** [SamVerschueren/ama#13]
No cheating with the obvious "I needed it for X." You have to start somewhere and most people brainstorm for fun. What do you do?

**Comment by SamVerschueren** [comment]
Hi @sholladay, thanks for the question!

Well, some projects really started as "I needed it for X". Take [listr](https://github.com/SamVerschueren/listr) for example, the idea of creating that UI came from [this post](https://github.com/sindresorhus/np/issues/30#issuecomment-224189149) when discussing the UI of `np`. At first I was implementing that inside of `np`, but then I thought "Maybe other people could make use of that too".

The same thing goes for [bragg](https://github.com/SamVerschueren/bragg). I wanted an express-like framework for AWS Lambda because I use Lambda quite heavily at my job. Creating `Bragg` made the code so much simpler and cleaner and easier to maintain. So yes, again, "I needed it for my job" ;).

But I agree, not everything happens because I needed it for something. Sometimes you just come up with an idea like "it would be nice if we could do that". Most of the times these ideas pop in my head while I'm not working. For instance while riding my bike or sitting on the train, not when I'm developing. This happened with [dev-time](https://github.com/SamVerschueren/dev-time-cli) for instance. I was contributing quite a lot with @sindresorhus, but he travels a lot. It's just a nice way of keeping track in which timezone he currently lives. Also quite a lot of things we use in [alfy](https://github.com/sindresorhus/alfy) just popped up in my head. "Wouldn't it be nice if we had update notifications". "Wouldn't it be nice if we could publish our workflows to npm". Not because I really need them, just because it's fun to do and it makes things so much easier.

And that's also what I love on creating tools rather then products. It could really boost your day to day productivity. Sindre and I created a couple of these Alfred workflows which I maybe use 100 of times a day like [alfred-npms](https://github.com/sindresorhus/alfred-npms) or [alfred-ng2](https://github.com/SamVerschueren/alfred-ng2). Seriously, since I have those, I can't decently work without them. And these workflows, for me personally, are also created because I thought it was fun to do and "Wouldn't it be nice if I could search the Angular 2 docs from within Alfred". And afterwards it turns out that it makes me so much more productive.

So the end this with a conclusion. I don't brainstorm like sitting on my desk and thinking "What could I create?". It's more that things are popping up in my head and I just create it. The ideas just come in my head automatically. Why? I have no idea. Maybe because I like making myself more productive? And sometimes just because "let's see if we can do this" because if you never try, you will never know ;).

I hope this answers your question :)?

**Comment by SamVerschueren** [comment]
Oh and as an extra add on to this answer. Don't focus on creating projects for likes/stars and followers. Create them because you love what you do and because you think it's awesome. To me that's far more important than creating the next big thing...

**Comment by sholladay** [comment]
> Well, some projects really started as "I needed it for X".

For sure! But I think if we look at the chain of these as an idea tree, somewhere at the root we may often find a whim or highly artistic - rather than utilitarian - idea. The rest can be seen as the implementation or dependencies.

> The same thing goes for bragg. I wanted an express-like framework for AWS Lambda

This is awesome. Definitely going to try it out.

> Maybe because I like making myself more productive?

That tends to be my motivation as well. I think it's a good one, though it tends to lead me to work on obscure tooling rather than apps.

Thanks!
