### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/ama#2]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by SamVerschueren** [comment]
I have a 15" MacBook Pro.

My main browser is definitely Chrome. Don't see why I would use another one to be honest.

My favorite text editor is [VS Code](https://www.visualstudio.com/en-us/products/code-vs.aspx) with the `dark+` theme. Honestly, I don't see why someone would ever develop on a text editor with a white theme. I don't like to start a text editor war because I think everyone should use the one he likes most and is the most productive with. It lacked extensions in the beginning (beta phase), but created some of my own like the [XO](https://github.com/samverschueren/vscode-linter-xo) plugin and the [AVA](https://github.com/samverschueren/vscode-ava) snippets. I also contributed to the [EditorConfig](https://github.com/editorconfig/editorconfig-vscode) plugin. These are my most used plugins in VS Code.

I like HyperTerminal with the [snazzy](https://github.com/sindresorhus/hyperterm-snazzy) theme quite a lot, especially the plugin part. Although I miss some of the features like vertical/horizontal splitting and clickable links. Tried to create a plugin for the clickable links but couldn't find out how to do it :(.

I read about [Alfred](https://www.alfredapp.com/) on your AMA and checked it out. Didn't see any real benefit over the default Spotlight. But man, did your [npms](https://github.com/sindresorhus/alfred-npms) workflow changed that. Instantly bought the powerpack to be able to use it. I use it everyday together with my own [ng2](https://github.com/samverschueren/alfred-ng2) workflow. Those two already saved me quite some time.

I use [nvm](https://github.com/creationix/nvm) as node version manager and [np](https://github.com/sindresorhus/np) to release my packages. Off course also [yo](http://yeoman.io/) to scaffold out projects. The generators I use the most are [generator-nm](https://github.com/sindresorhus/generator-nm) and [generator-aws-lambda](https://github.com/SamVerschueren/generator-aws-lambda). I hope to add [generator-alfred](https://github.com/SamVerschueren/generator-alfred) to my most used generators soon :).

I mainly use the cli to do my git stuff, but when it gets to tricky, I switch to [SourceTree](https://www.sourcetreeapp.com/).

I guess this covers all. If you think I missed something, feel free to ask :).

**Comment by mikemcbride** [comment]
> Although I miss some of the features like vertical/horizontal splitting and clickable links.

someone has a plugin for this (just the links part) and it's awesome: https://www.npmjs.com/package/hyperlinks 👍

**Comment by SamVerschueren** [comment]
Alright, this is really awesome! Thanks for bringing that up @mmcbride1007!
