### ISSUE TITLE
What do you do when you're not programming?

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/ama#4]

**Comment by SamVerschueren** [comment]
Good question :p.

I spend quite some time with my family as I also have a daughter. I actually never spend time on my computer when she's at home (and awake :)). 

I try to go out a couple of times for a run during the week and I play football (soccer for the englishmen) during the weekend. 

I also read tech books and blogs. I like to read on paper though. So when I buy a book, I don't care spending some extra money to get a printed copy instead of an ebook. I don't want to spend more time behind a screen then I already do for reading a book.

And in the evenings, I sometimes watch some television or go out for a drink with my girlfriend.

**Comment by sindresorhus** [comment]
> I spend quite some time with my family as I also have a daughter.

Ah, I didn't realize you have a daughter. That's great :)

> I actually never spend time on my computer when she's at home (and awake :)).

I try to do the same with girlfriend too.

**Comment by SamVerschueren** [comment]
> Ah, I didn't realize you have a daughter. That's great :)

Yes, she's amazing :)!
